spring.config.import=optional:file:.env[.properties]
spring.application.name=mandilas-market-server

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/mandilas_market?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=@Emma124

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}
paystack.secret-key=${PAYSTACK_SECRET_KEY}